ZAD 1A
CREATE TABLE S6_LRS (
    geom SDO_GEOMETRY
);

ZAD 1B
INSERT INTO S6_LRS (geom)
SELECT s.geom
FROM STREETS_AND_RAILROADS s
JOIN MAJOR_CITIES c ON c.city_name = 'Koszalin'
WHERE SDO_RELATE(
        s.geom,
        SDO_GEOM.SDO_BUFFER(c.geom, 10, 1, 'unit=km'),
        'MASK=ANYINTERACT'
    ) = 'TRUE';

ZAD 1C
SELECT SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE,
    ST_LINESTRING(GEOM).ST_NUMPOINTS() ST_NUMPOINTS
FROM S6_LRS;

ZAD 1D
UPDATE S6_LRS
SET geom = SDO_LRS.CONVERT_TO_LRS_GEOM(
  geom,
  0,
  SDO_GEOM.SDO_LENGTH(geom, 0.005)
);

ZAD 1E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
    'S6_LRS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', 0, 1000, 0.005),
        SDO_DIM_ELEMENT('Y', 0, 1000, 0.005),
        SDO_DIM_ELEMENT('M', 0, 300, 0.005)
    ),
    8307
);

ZAD 1F
CREATE INDEX S6_LRS_IDX ON S6_LRS(GEOM)
indextype IS MDSYS.SPATIAL_INDEX;

ZAD 2A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM S6_LRS;

ZAD 2B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM S6_LRS;

ZAD 2C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150
FROM S6_LRS;

ZAD 2D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM S6_LRS;

ZAD 2E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(S6.GEOM, C.GEOM) WJAZD_NA_A6
FROM S6_LRS S6, MAJOR_CITIES C
WHERE C.CITY_NAME = 'Slupsk';

ZAD 2F
SELECT
    SDO_GEOM.SDO_LENGTH(
        SDO_LRS.CLIP_GEOM_SEGMENT(geom, 50, 200),
        0.005
    ) AS koszt
FROM S6_LRS;